def get_years_names(txt):
    step_one=open(txt)
    step_two=step_one.read()
    finished_name_list=step_two.split()
    return finished_name_list

get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1880.txt")

eighteeneighty=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1880.txt")
eighteeneightyone=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1881.txt")
eighteeneightytwo=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1882.txt")
eighteeneightythree=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1883.txt")
eighteeneightyfour=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1884.txt")
eighteeneightyfive=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1885.txt")
eighteeneightysix=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1886.txt")
eighteeneightyseven=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1887.txt")
eighteeneightyeight=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1888.txt")
eighteeneightynine=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1889.txt")
eighteenninety=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1890.txt")
eighteenninetyone=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1891.txt")
eighteenninetytwo=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1892.txt")
eighteenninetythree=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1893.txt")
eighteenninetyfour=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1894.txt")
eighteenninetyfive=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1895.txt")
eighteenninetysix=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1896.txt")
eighteenninetyseven=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1897.txt")
eighteenninetyeight=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1898.txt")
eighteenninetynine=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1899.txt")
nineteenhundred=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1900.txt")
nineteenhundredone=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1901.txt")
nineteenhundredtwo=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1902.txt")
nineteenhundredthree=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1903.txt")
nineteenhundredfour=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1904.txt")
nineteenhundredfive=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1905.txt")
nineteenhundredsix=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1906.txt")
nineteenhundredseven=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1907.txt")
nineteenhundredeight=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1908.txt")
nineteenhundrednine=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1909.txt")
nineteenten=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1910.txt")
nineteeneleven=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1911.txt")
nineteentwelve=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1912.txt")
nineteenthirteen=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1913.txt")
nineteenfourteen=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1914.txt")
nineteenfifteen=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1915.txt")
nineteensixteen=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1916.txt")
nineteenseventeen=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1917.txt")
nineteeneighteen=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1918.txt")
nineteennineteen=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1919.txt")
nineteentwenty=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1920.txt")
nineteentwentyone=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1921.txt")
nineteentwentytwo=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1922.txt")
nineteentwentythree=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1923.txt")
nineteentwentyfour=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1924.txt")
nineteentwentyfive=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1925.txt")
nineteentwentysix=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1926.txt")
nineteentwentyseven=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1927.txt")
nineteentwentyeight=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1928.txt")
nineteentwentynine=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1929.txt")
nineteenthirty=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1930.txt")
nineteenthirtyone=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1931.txt")
nineteenthirtytwo=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1932.txt")
nineteenthirtythree=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1933.txt")
nineteenthirtyfour=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1934.txt")
nineteenthirtyfive=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1935.txt")
nineteenthirtysix=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1936.txt")
nineteenthirtyseven=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1937.txt")
nineteenthirtyeight=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1938.txt")
nineteenthirtynine=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1939.txt")
nineteenfourty=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1940.txt")
nineteenfourtyone=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1941.txt")
nineteenfourtytwo=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1942.txt")
nineteenfourtythree=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1943.txt")
nineteenfourtyfour=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1944.txt")
nineteenfourtyfive=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1945.txt")
nineteenfourtysix=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1946.txt")
nineteenfourtyseven=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1947.txt")
nineteenfourtyeight=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1948.txt")
nineteenfourtynine=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1949.txt")
nineteenfifty=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1950.txt")
nineteenfiftyone=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1951.txt")
nineteenfiftytwo=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1952.txt")
nineteenfiftythree=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1953.txt")
nineteenfiftyfour=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1954.txt")
nineteenfiftyfive=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1955.txt")
nineteenfiftysix=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1956.txt")
nineteenfiftyseven=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1957.txt")
nineteenfiftyeight=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1958.txt")
nineteenfiftynine=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1959.txt")
nineteensixty=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1960.txt")
nineteensixtyone=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1961.txt")
nineteensixtytwo=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1962.txt")
nineteensixtythree=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1963.txt")
nineteensixtyfour=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1964.txt")
nineteensixtyfive=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1965.txt")
nineteensixtysix=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1966.txt")
nineteensixtyseven=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1967.txt")
nineteensixtyeight=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1968.txt")
nineteensixtynine=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1969.txt")
nineteenseventy=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1970.txt")
nineteenseventyone=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1971.txt")
nineteenseventytwo=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1972.txt")
nineteenseventythree=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1973.txt")
nineteenseventyfour=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1974.txt")
nineteenseventyfive=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1975.txt")
nineteenseventysix=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1976.txt")
nineteenseventyseven=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1977.txt")
nineteenseventyeight=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1978.txt")
nineteenseventynine=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1979.txt")
nineteeneighty=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1980.txt")
nineteeneightyone=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1981.txt")
nineteeneightytwo=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1982.txt")
nineteeneightythree=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1983.txt")
nineteeneightyfour=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1984.txt")
nineteeneightyfive=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1985.txt")
nineteeneightysix=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1986.txt")
nineteeneightyseven=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1987.txt")
nineteeneightyeight=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1988.txt")
nineteeneightynine=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1989.txt")
nineteenninety=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1990.txt")
nineteenninetyone=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1991.txt")
nineteenninetytwo=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1992.txt")
nineteenninetythree=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1993.txt")
nineteenninetyfour=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1994.txt")
nineteenninetyfive=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1995.txt")
nineteenninetysix=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1996.txt")
nineteenninetyseven=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1997.txt")
nineteenninetyeight=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1998.txt")
nineteenninetynine=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1999.txt")
twothousand=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob2000.txt")
twothousandone=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob2001.txt")
twothousandtwo=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob2002.txt")
twothousandthree=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob2003.txt")
twothousandfour=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob2004.txt")
twothousandfive=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob2005.txt")
twothousandsix=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob2006.txt")
twothousandseven=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob2007.txt")
twothousandeight=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob2008.txt")
twothousandnine=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob2009.txt")
twothousandten=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob2010.txt")
twothousandeleven=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob2011.txt")
twothousandtwelve=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob2012.txt")
twothousandthirteen=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob2013.txt")
twothousandfourteen=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob2014.txt")
twothousandfifteen=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob2015.txt")
twothousandsixteen=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob2016.txt")
twothousandseventeen=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob2017.txt")
twothousandeighteen=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob2018.txt")
twothousandnineteen=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob2019.txt")
twothousandtwenty=get_years_names("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob2020.txt")

def rewrite_txt_with_array(txtfile,arrayoftxt):
    ourtxt= open(txtfile,"w")
    stringofarray=str(arrayoftxt)
    ourtxt.write(stringofarray)
    ourtxt.close()


rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/testfile.txt",nineteensixtynine)


rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob2020.txt",twothousandtwenty)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob2019.txt",twothousandnineteen)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob2018.txt",twothousandeighteen)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob2017.txt",twothousandseventeen)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob2016.txt",twothousandsixteen)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob2015.txt",twothousandfifteen)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob2014.txt",twothousandfourteen)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob2013.txt",twothousandthirteen)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob2012.txt",twothousandtwelve)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob2011.txt",twothousandeleven)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob2010.txt",twothousandten)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob2009.txt",twothousandnine)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob2008.txt",twothousandeight)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob2007.txt",twothousandseven)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob2006.txt",twothousandsix)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob2005.txt",twothousandfive)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob2004.txt",twothousandfour)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob2003.txt",twothousandthree)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob2002.txt",twothousandtwo)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob2001.txt",twothousandone)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob2000.txt",twothousand)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1999.txt",nineteenninetynine)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1998.txt",nineteenninetyeight)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1997.txt",nineteenninetyseven)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1996.txt",nineteenninetysix)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1995.txt",nineteenninetyfive)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1994.txt",nineteenninetyfour)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1993.txt",nineteenninetythree)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1992.txt",nineteenninetytwo)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1991.txt",nineteenninetyone)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1990.txt",nineteenninety)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1989.txt",nineteeneightynine)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1988.txt",nineteeneightyeight)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1987.txt",nineteeneightyseven)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1986.txt",nineteeneightysix)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1985.txt",nineteeneightyfive)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1984.txt",nineteeneightyfour)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1983.txt",nineteeneightythree)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1982.txt",nineteeneightytwo)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1981.txt",nineteeneightyone)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1980.txt",nineteeneighty)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1979.txt",nineteenseventynine)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1978.txt",nineteenseventyeight)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1977.txt",nineteenseventyseven)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1976.txt",nineteenseventysix)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1975.txt",nineteenseventyfive)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1974.txt",nineteenseventyfour)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1973.txt",nineteenseventythree)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1972.txt",nineteenseventytwo)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1971.txt",nineteenseventyone)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1970.txt",nineteenseventy)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1969.txt",nineteensixtynine)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1968.txt",nineteensixtyeight)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1967.txt",nineteensixtyseven)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1966.txt",nineteensixtysix)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1965.txt",nineteensixtyfive)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1964.txt",nineteensixtyfour)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1963.txt",nineteensixtythree)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1962.txt",nineteensixtytwo)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1961.txt",nineteensixtyone)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1960.txt",nineteensixty)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1959.txt",nineteenfiftynine)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1958.txt",nineteenfiftyeight)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1957.txt",nineteenfiftyseven)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1956.txt",nineteenfiftysix)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1955.txt",nineteenfiftyfive)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1954.txt",nineteenfiftyfour)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1953.txt",nineteenfiftythree)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1952.txt",nineteenfiftytwo)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1951.txt",nineteenfiftyone)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1950.txt",nineteenfifty)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1949.txt",nineteenfourtynine)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1948.txt",nineteenfourtyeight)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1947.txt",nineteenfourtyseven)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1946.txt",nineteenfourtysix)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1945.txt",nineteenfourtyfive)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1944.txt",nineteenfourtyfour)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1943.txt",nineteenfourtythree)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1942.txt",nineteenfourtytwo)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1941.txt",nineteenfourtyone)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1940.txt",nineteenfourty)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1939.txt",nineteenthirtynine)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1938.txt",nineteenthirtyeight)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1937.txt",nineteenthirtyseven)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1936.txt",nineteenthirtysix)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1935.txt",nineteenthirtyfive)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1934.txt",nineteenthirtyfour)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1933.txt",nineteenthirtythree)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1932.txt",nineteenthirtytwo)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1931.txt",nineteenthirtyone)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1930.txt",nineteenthirty)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1929.txt",nineteentwentynine)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1928.txt",nineteentwentyeight)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1927.txt",nineteentwentyseven)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1926.txt",nineteentwentysix)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1925.txt",nineteentwentyfive)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1924.txt",nineteentwentyfour)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1923.txt",nineteentwentythree)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1922.txt",nineteentwentytwo)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1921.txt",nineteentwentyone)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1920.txt",nineteentwenty)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1919.txt",nineteennineteen)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1918.txt",nineteeneighteen)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1917.txt",nineteenseventeen)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1916.txt",nineteensixteen)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1915.txt",nineteenfifteen)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1914.txt",nineteenfourteen)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1913.txt",nineteenthirteen)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1912.txt",nineteentwelve)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1911.txt",nineteeneleven)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1910.txt",nineteenten)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1900.txt",nineteenhundred)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1901.txt",nineteenhundredone)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1902.txt",nineteenhundredtwo)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1903.txt",nineteenhundredthree)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1904.txt",nineteenhundredfour)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1905.txt",nineteenhundredfive)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1906.txt",nineteenhundredsix)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1907.txt",nineteenhundredseven)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1908.txt",nineteenhundredeight)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1909.txt",nineteenhundrednine)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1890.txt",eighteenninety)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1891.txt",eighteenninetyone)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1892.txt",eighteenninetytwo)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1893.txt",eighteenninetythree)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1894.txt",eighteenninetyfour)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1895.txt",eighteenninetyfive)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1896.txt",eighteenninetysix)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1897.txt",eighteenninetyseven)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1898.txt",eighteenninetyeight)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1899.txt",eighteenninetynine)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1880.txt",eighteeneighty)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1881.txt",eighteeneightyone)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1882.txt",eighteeneightytwo)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1883.txt",eighteeneightythree)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1884.txt",eighteeneightyfour)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1885.txt",eighteeneightyfive)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1886.txt",eighteeneightysix)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1887.txt",eighteeneightyseven)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1888.txt",eighteeneightyeight)
rewrite_txt_with_array("/Users/wschierenbeck/Development/code/baby_name_generator/babynamegenerator/names/yob1889.txt",eighteeneighty)
































